livy.spark.master = local[*]
livy.spark.deploy-mode = client
livy.file.local-dir-whitelist = /app
livy.server.session.timeout = 1h
livy.spark.sql.extensions = io.delta.sql.DeltaSparkSessionExtension
livy.spark.sql.catalog.spark_catalog = org.apache.spark.sql.delta.catalog.DeltaCatalog